### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by LaysDragon** [LaysDragon/rukr_chromatic_orb#1]
- [ ] 集成功能的台詞觸發管理器
  - [ ] 可以設置觸發條件的台詞
  - [ ] 只能被使用一次的台詞
  - [ ] 台詞可以是一組隨機組合
  - [ ] 台詞可以是一個方法
- [ ] 重新設計聲音反應邏輯，集中註冊不同物件之間的聲音組合?(但還能保持動態性?)
- [ ] 用事件來處理orb消耗事件
- [ ] 部分事件應能夠從事件監聽處取消/阻止事件發生
- [ ] 互動事件並設置互動結果:無(之後要能無視與該物件的後續碰撞?)、已銷毀、已消耗、已彈開(預設值?)
- [ ] 銷毀掉出世界外的物件，同時也會要觸發miss事件
- [ ] 以物件為本位調整系統，而不是以character為本位設計
  - [ ] 可以得知互動來源的操作事件:hurt,death,counter,cocollision,effect apply,miss
  - [ ] 目前遊戲內存在主體:character,orb,player
- [ ] 將三色石中毒計數器與orb計數器分開放到poe module單獨管理
- [ ] 通過counter事件觸發的death要將來源設置為counter的來源物件
